// features.js
const features = [
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌CH1ND0 NG3R1NT1H 4T1T S0S1S P4C4R',
        link: 'https://cdn.videy.co/b1G8yXYp1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B1K1N K0NTENT S44T M4ND1 BU4T FWB',
        link: 'https://cdn.videy.co/mlOet1IZ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌DU0 S4H4B4T J4D1 L3B10L4',
        link: 'https://cdn.videy.co/hw1IhoQj1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌C4NT1K T4P1 L0NGG4R',
        link: 'https://cdn.videy.co/BZ24yStF1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4NT4VNY4 G4Y4 GUKGUK S4M4 D0S3N',
        link: 'https://cdn.videy.co/sg3YnMmz1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌BR0C1UL ESYEMPE 0M3G',
        link: 'https://cdn.videy.co/zX1onzHa1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌4BG NG3MYUT C0C2S P4C4R',
        link: 'https://cdn.videy.co/1X3vc1SR1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌SI C4NT1K B3RKUL1T S4W0 M4T4NG L1V3 0M3G',
        link: 'https://cdn.videy.co/JP1gP1rj1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌DI G0Y4NK J-ND4 S4MP3 L3M4YS',
        link: 'https://cdn.videy.co/o6yW7S1d1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4C4R BUL3 NG3NTD DI 4P4RT3M3N',
        link: 'https://cdn.videy.co/VBq4dtjn1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌J-ND4 0M3G B3RTIG4 S4MP3 M0NCRT',
        link: 'https://cdn.videy.co/nSBSsyy71.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌PL4J4R 3SY3MP3H JU4L4N K0NT3NT',
        link: 'https://cdn.videy.co/MMkR6JF31.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌CWE B3RM4SK3R REL4 DI J1LMG',
        link: 'https://cdn.videy.co/5ghsaaIr1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌BR0C1OUL 3SYEMPEH M4U 4J3 DI GNGB*NG',
        link: 'https://cdn.videy.co/WXQPUGo41.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌G4R4P P4C4R & 1BV P4C4R',
        link: 'https://cdn.videy.co/yR6lIAt31.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌DI EW S4MP3 P1NGS4N S4M4 GURU',
        link: 'https://cdn.videy.co/PtJTENiP1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S3L1NGKH S4M4 T3T4NGG4 DI RU4NG T4MU',
        link: 'https://cdn.videy.co/HA1wUqnm1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P0LW4N B4RU J4D1 UD4H NGW S4M4 S3N10R',
        link: 'https://cdn.videy.co/58rfkHhW1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌ESYEMPE 0M3G D3NG4N B0T0L',
        link: 'https://cdn.videy.co/iH6ohaVk1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌K3N4L4N D4R1 FB, K3T3MU L4NGSUNG NGW DI 0Y0',
        link: 'https://cdn.videy.co/bysMhBq81.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌4BG NGW G4Y4 DU0GHY M4Y0 NY4 S4MP3 BERC3C3R',
        link: 'https://cdn.videy.co/jtInc2yT1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌ASYUPAN 4NK TELE V1R4L',
        link: 'https://cdn.videy.co/YgNolABU1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1JB NK4L 0M3G B4SY4H B3RLND1R',
        link: 'https://cdn.videy.co/2TJLyo3p1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4H4S1SW4 KUMPUL K3B0 D1 GR3B3K W4RG4',
        link: 'https://cdn.videy.co/635vRxBR1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌C0SPL4Y DI D3P4N SUW4M1',
        link: 'https://cdn.videy.co/xcF5wtY11.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1 1K4T L4LU D1 EW 4DK & T3M4N"NY4',
        link: 'https://cdn.videy.co/3EPiveSL1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌ARSIP L4NGK4 S4M4 P4C4R',
        link: 'https://cdn.videy.co/FBW6OB6j1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌ABG M41N S4M4 W4RW3RW0R',
        link: 'https://cdn.videy.co/xIhtkYO71.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S3L1NGKH S4M4 P4K RT',
        link: 'https://cdn.videy.co/TgOTwgZ41.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4LM1NG4N S4M4 4Y4NK DI 0Y0',
        link: 'https://cdn.videy.co/RmM5YRGc1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M3SYUM DI M0B1L S3MBUNY1',
        link: 'https://cdn.videy.co/UmX4T7BO1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌BE.0 CWE K0R3A DI HUT4N',
        link: 'https://cdn.videy.co/qozoIpic1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌DU0GHY JUR4G4N K0NTR4K4N',
        link: 'https://cdn.videy.co/2Okuj3TE1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S4D4P CCTV DI RUM4H T3T4NGG4',
        link: 'https://cdn.videy.co/VEFSYfqX1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B0S T4MBR4NG NGW LC D1 H0TL',
        link: 'https://cdn.videy.co/WCGuw9pY1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4K3 G4Y4 W0T S4MP3 K3LU4R D1D4L3M',
        link: 'https://cdn.videy.co/yEifmcc11.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1J4B T0WC13L S4GN3 P4S L4G1 S3ND1RI',
        link: 'https://cdn.videy.co/4PaDhH2C1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N93NT0Y S4M4 P4C4R S4MP3 L3M3S',
        link: 'https://cdn.videy.co/gPmSuTv61.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M41N B4R3NG AY4NG S4MB1L N3LP0N',
        link: 'https://s.id/videy_co-vidzTgbo55Z1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S4M4 D0S3N D3M1 N1L41 B4GVS',
        link: 'https://cdn.videy.co/NYnqb4iX1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌V1D3O PR1BR4D1 D1S3B4R M4NT4N',
        link: 'https://cdn.videy.co/W82V60ns1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N93NT0Y S4M4 J4ND4 MVD4 H0T',
        link: 'https://cdn.videy.co/WPvM6ys81.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P3LAJ4R PVL4NG S3KOL4H B1R4H1',
        link: 'https://cdn.videy.co/Ot71QH3U1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌G4S4K AY4NG Y4NG L4G1 T3P4R',
        link: 'https://cdn.videy.co/OwadGdlZ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌BVND3 G3M0Y Y4NG P3NVH N4FSV',
        link: 'https://cdn.videy.co/PXuhWBFE1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌C3W3K AR4B M41N TR1S0M3',
        link: 'https://cdn.videy.co/ocAKWEIZ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌C3W3KNY4 P3RT4M4 K4L1 M41N D1AT4S',
        link: 'https://cdn.videy.co/0SadI7QD1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌ESP3G3 B3N1NG P1NT3R G0Y4NG D1AT4S',
        link: 'https://cdn.videy.co/PoX2yshq1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N93D0GGY J4ND4 D4ST3R KVN1NG',
        link: 'https://cdn.videy.co/pqMBvTpI1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B3R0ND0NG D1UL3K1N S4M4 T4NT3 C4NT1K',
        link: 'https://cdn.videy.co/tAaF9NWy1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌ESYEMAH 0M3G M4S2H P4K3 SR4G4M',
        link: 'https://cdn.videy.co/GsnmR4La1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌V0K3P 1ND14 J1LMQ 1P4R',
        link: 'https://cdn.videy.co/hTVffXGo1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌G4D1S PRWN M4L4Y 0M3G DI K4M4R',
        link: 'https://cdn.videy.co/KghhbDcF1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌NY0B4 4P3M BUL3 GUNDUL. 4NG3T BGT CUY',
        link: 'https://cdn.videy.co/nFlRTXlp1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌VUG1L DI UMUM',
        link: 'https://cdn.videy.co/CJnrKzHf1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌STW T0BRT S3NENG DI R3M3S"',
        link: 'https://cdn.videy.co/neCz3q9w1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌KULUPNY4 M4S1H 4D4. N4MUN B1K1N M30NG 4P3M J-ND4 B3CY3K',
        link: 'https://cdn.videy.co/seG1RiDP1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4M3R BDY DI K4M4R 4YH',
        link: 'https://cdn.videy.co/CmRPdFcY1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌CH1ND0 T0Q3T BUY3T DI EW KK4K KNDG',
        link: 'https://cdn.videy.co/VhvG49ZI1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌UGH AH, S4K1T T4P1 N1KMTNY4 NGW B1N0R',
        link: 'https://cdn.videy.co/DAWRSwc91.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌DI SUNDUL C0C1S 4Y4NK',
        link: 'https://cdn.videy.co/Mstl6VFw1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌DU0GHY EL SI DI RUM4H P3L4NGG4N',
        link: 'https://cdn.videy.co/vlOh8Mam1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌MSBRAW NYENDER1N M30NGNY4 KE W4J4H 4Y*H',
        link: 'https://cdn.videy.co/fKzLMvcY1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌CWE B3RC4D4R 0M3G D1 T01L3T S3KUL',
        link: 'https://cdn.videy.co/SQyM1Kns1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B4W4 P4C4R BU4T D1 EW S4M4 T3M3N"NY4',
        link: 'https://cdn.videy.co/XZ7aPPXT1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌PUL4NG S3KUL L4NGSUNG D1 TDUR1N 4YH',
        link: 'https://cdn.videy.co/mrUfkupY1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌1NT1P P0N4K4N M4ND1',
        link: 'https://cdn.videy.co/IIu61XIB1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B3RH1JB T4P1 S3R1NG K3 H0TL',
        link: 'https://cdn.videy.co/vQEQllpJ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1JB H0BY 1K4T" S3B3LUM M41N',
        link: 'https://cdn.videy.co/JRea07mg1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4H4S1SW1 & P4C4RNY4 D1 K0S4N B1K1N S3SU4TU 😭',
        link: 'https://cdn.videy.co/hqoj3cBQ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B1K1N T1KT0K G4K P4K3 B4JUL4LU D1 1NT1P 4Y4H & D1 K3MPRUTZ K3MUD14N',
        link: 'https://cdn.videy.co/AQZHOHSD1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌TUK4NG P1J3T M3SYUM',
        link: 'https://cdn.videy.co/TkScmFl21.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌SK4NDL D0KT3R C4NT1K',
        link: 'https://cdn.videy.co/aR600pIG1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4KZ4 1BV T1R1 BU4T L4Y4NN PUL4NG S3KUL',
        link: 'https://cdn.videy.co/uw6RvEm41.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌CWE G4UL H1JB J4KS3L',
        link: 'https://cdn.videy.co/EzdmZQUX1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌PL4J4R 3SY3MP3H JU4L4N K0NT3NT D3M1 U4NG Z3KUL',
        link: 'https://cdn.videy.co/MMkR6JF31.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌CWE B3RM4SK3R R3L4 D1 J1LMG STR4NG3R K4R3N4 S4M4" 3MG4S',
        link: 'https://cdn.videy.co/5ghsaaIr1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌G4R4P P4C4R & 1BV P4C4R',
        link: 'https://cdn.videy.co/yR6lIAt31.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B1DUW4N J4K4RT4 D1 GL1R R4M "',
        link: 'https://cdn.videy.co/LAHtmxa11.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌4B3G3H PRWN D1 P3RKR40S B0K4P"',
        link: 'https://cdn.videy.co/wSZAeIPx1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B3CY3K S4MP3 L3CY3T D1 SD0K GURU',
        link: 'https://cdn.videy.co/MlXHSYlV1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌CRTS D1 MUK4 D0S3N C4NT1K',
        link: 'https://cdn.videy.co/2FmfmGF41.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌L3SB10L4 G4K M4U L3P4S1N J1LT4N',
        link: 'https://cdn.videy.co/yrxzPLJv1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1 SRUPUT S4MP3 K3 1TW1L"NY4',
        link: 'https://cdn.videy.co/7xxwjxM21.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4RTY S3GH D3NG4N T3M4N" D1 PUNC4K',
        link: 'https://cdn.videy.co/7YK8svy01.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1 0M3G, D1 J1LT, D1 EW PU4S S4M4 CWE K3N4L4N B4RU',
        link: 'https://cdn.videy.co/COwGFrjd1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌K3N4L D4R1 T1ND1R D1 P3RKR40S',
        link: 'https://cdn.videy.co/DQJZ5GXy1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M30NG 4DK B3CY3K 4B1S D1 Q0B3L KK4K T1R1',
        link: 'https://cdn.videy.co/sPBmWglk1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌L1D4H 1BV M4SYUK K3 M30NG 4NK',
        link: 'https://cdn.videy.co/VlJa12MG1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M0U1U$ B4N93T PUNY4 D3D3',
        link: 'https://cdn.videy.co/tjpfFMRu1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4M4N K33N4K4N D1P1J3T',
        link: 'https://cdn.videy.co/SIWbey3Z1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S1C4NT1K SUK4 J31AT',
        link: 'https://cdn.videy.co/ZsWjy2W51.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1J31AT 4K4K',
        link: 'https://cdn.videy.co/0ybmRx1C1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S14K4K M43N D31D0',
        link: 'https://cdn.videy.co/3vi9qmeW1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌4NT3 K33N4K4N D9Y',
        link: 'https://cdn.videy.co/W2qghy841.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M43N 4M4 4NT3',
        link: 'https://cdn.videy.co/m41uTBCP1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S1C4NT1K N91D3M N90CK',
        link: 'https://cdn.videy.co/rnF0oKUY1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1J31AT D3D3 D1M0B1L',
        link: 'https://cdn.videy.co/tMYRPIAn1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S1C4NT1K DR3SS M3R4',
        link: 'https://cdn.videy.co/8KpAgmV81.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D3D3 94N99U1N 4B9 L491 T1DUR',
        link: 'https://cdn.videy.co/EVpNQ76j1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D9Y 4M4 4K4K',
        link: 'https://cdn.videy.co/HlulSp811.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌4NT3 T4T04N',
        link: 'https://cdn.videy.co/vy9zroIv1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S1C4NT1K 0W3 S3ND1R1',
        link: 'https://cdn.videy.co/fv58VSUj1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D01SUK4 D14T4$',
        link: 'https://cdn.videy.co/wSdMKTkf1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1S3W T3MN K4NT0R',
        link: 'https://cdn.videy.co/XcdV2aIl1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1J4B3RS C4NT1K M4NT3P B4NG3T',
        link: 'https://cdn.videy.co/SmPncge21.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌G4D1S K4CAM4T4 S3M0KS N9ENT0Y',
        link: 'https://cdn.videy.co/mQvbTqWJ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S4GN3 B4NG3T L1AT B0DYNY4',
        link: 'https://cdn.videy.co/JcxHAG0x1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N91NT1P K4K4K T1R1 M4STVB4S1',
        link: 'https://cdn.videy.co/TlkweI4K1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N93NT0Y M1M1W S3MP1T AY4NG',
        link: 'https://cdn.videy.co/KVyhfg3g1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N93NT0Y K4RYAW4T1 P4NT4T S3M0KS',
        link: 'https://cdn.videy.co/5CqBUTmL1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S4K1NG N1KM4TNYA S4MP3 B3C3K',
        link: 'https://cdn.videy.co/ao4EbqFz1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N91NT1P T3T4NGG4 K0ST BVWG1L',
        link: 'https://cdn.videy.co/CankXaot1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N91CL1K T3M3N S4MP3 M3ND3S4H',
        link: 'https://cdn.videy.co/zZL5BlSM1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌EN4K B4NG3T PVNY4 AY4NG HYP3R',
        link: 'https://cdn.videy.co/tvuLiY151.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌K3S4K1T4N D1ENT0Y S4M4 0M',
        link: 'https://cdn.videy.co/PGYUMTgf1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌EN4KNY4 PUNY4 AD3K Y4NG P3NVRUT',
        link: 'https://cdn.videy.co/QuFKBQVZ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌J1LM3Q1N M1M1W MVLUS AY4NG',
        link: 'https://cdn.videy.co/KKtjliLc1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N93G4R4P AD3K K4NDVNG S3ND1R1',
        link: 'https://cdn.videy.co/SEN6r2nE1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌T4NT3 NG4J4KIN M41N DR1V3R 0J0L',
        link: 'https://cdn.videy.co/JVQ70kOX1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4S4NG4N AB9 M3SVM D1W4RVNG',
        link: 'https://cdn.videy.co/HTvKlES11.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌3 C3W3K CH1ND0 L4G1 P3ST4 S3K',
        link: 'https://cdn.videy.co/FZcKt7sZ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4SR4H D1ENT0Y S4M4 AY4NG',
        link: 'https://cdn.videy.co/rDKSxNbU1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌BUL3T PUL3N 0M3GG',
        link: 'https://cdn.videy.co/QsbO4eB01.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌NGW D1 P0H0N K3L4P4 S4M4 KK3K',
        link: 'https://cdn.videy.co/ycl4qkxi1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B3RT3DUH D1 GUBUK T1B4" 3NG4S J4D1 0M3G',
        link: 'https://cdn.videy.co/LaFCDMay1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S1 C4NT1K NG4J4K M4ND0R M3SYUM D1 RUM4H K0S0NG',
        link: 'https://cdn.videy.co/dLDZjODD1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌DR1V3R 0NL1N3 K3N4 R3J3K1 N0MPL0K K3T3MU T-NT3 S1SKR, D1 4J4K B1K1N K0NT3N ++',
        link: 'https://cdn.videy.co/TKg6gU9S1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌K3S3P13N SUW4M1 D1N4S. B1N0R NG4J4K 4JUD4N 4NU"',
        link: 'https://cdn.videy.co/QJEBGHzv1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌KK3K M4ND1K4N CUCU C4NT1K',
        link: 'https://cdn.videy.co/KdB4CGtQ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4L4M" NY3T1R S3ND1R1 T4P1 3MG4S. 4KH1RNY4 NG4J4K STR4NG3R B4NTU1N 0M3G',
        link: 'https://cdn.videy.co/XsuUVpUE1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌0J0L D1 K4S1H H4D14H S4M4 CUST0M3R HYPR. NGW GR4T1S P4RT 1',
        link: 'https://cdn.videy.co/a3MMXVT51.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌T3T4NGG4 M3SYUM, NG0M3Q1N 1STR1',
        link: 'https://cdn.videy.co/UvuiXQT81.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌1NT1P S1 C4NT1K S3L3BGR4M L1V3 ++ D1 1NSTA',
        link: 'https://cdn.videy.co/qFaF6jxT1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌4SD 3D1S1 CWE B4T4M D1 ENTD BUL3',
        link: 'https://cdn.videy.co/wqj6lQZd1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M3M3W J-ND4 1T4M T4P1 4NG3T',
        link: 'https://cdn.videy.co/SI5hPS9r1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1JB P1NT4R NGUL3G P4C4R',
        link: 'https://cdn.videy.co/q99uiqow1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌BUL3T PUL3N PUNY4 4RT',
        link: 'https://cdn.videy.co/ybi7yXH61.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S1 G3NDUT CUBBHY NGULYUM T0RN4D0 BUL3',
        link: 'https://cdn.videy.co/BoWgc1Ri1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌1NTP T3T4NGG4 0M3GH',
        link: 'https://cdn.videy.co/dMkGIvmg1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌C0C1S BUL3 B3LUM CUN4T D1 QULUM 4B1S',
        link: 'https://cdn.videy.co/sUPFQGri1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D0Y4N B3JY3H. M4Y0NY4 D1 T3L4N 4B13S',
        link: 'https://cdn.videy.co/hlv4RgBl1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌NG1NT1P T3T4NGG4 K0S3N L4G1 Q3NTU',
        link: 'https://cdn.videy.co/IqIdjXBN1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌1BV & 4NK NGNT0Y S44T RUM4H K0S0NG',
        link: 'https://cdn.videy.co/hBDFFDtQ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌T-NT3 J-ND4 NG4J4K B3RM41N D1 4P4RT3M3NT',
        link: 'https://cdn.videy.co/pXWjS8Fy1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌3SY3MP3H UD4H D1 L0B4NG1N PCR',
        link: 'https://cdn.videy.co/Djyswxla1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌K2 RUM3H T3M4N CUM4 4D4 1STR1NY4',
        link: 'https://cdn.videy.co/R3kzkB1M1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4M4 T1R1 G4NJ3N G0D4" 4NK',
        link: 'https://cdn.videy.co/JyCpXCyF1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌G3D1S B4T4M SPR++ D1 EW BUL3 4SD',
        link: 'https://cdn.videy.co/OX22wYPR1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌L4G1 M41N PS P4C4R 0M3S R4B4"',
        link: 'https://cdn.videy.co/pwBA5V7E1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B3RDU44N D3NG4N KK4K B3RUJUNG S4L1NG J3L4T P4RT 1',
        link: 'https://cdn.videy.co/gULaVoDs1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B3RDU44N D3NG4N KK4K B3RUJUNG S4L1NG J3L4T P4RT 2',
        link: 'https://cdn.videy.co/R11gavRp1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌L4G1 T1DUR D1 GR3V3 4DK',
        link: 'https://cdn.videy.co/onGnWGaB1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1JB STW M41N D33NG4N M3RTUA',
        link: 'https://cdn.videy.co/HjVn1ELD1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌K4KK SNG3 S4M4 1BV KNDG S3ND1R1 UNC3NS0R3D P4RT 1',
        link: 'https://cdn.videy.co/YTBa6iBS1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌MM4 NGW S4M4 4NK T1R1',
        link: 'https://cdn.videy.co/Z1ctx14Y1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌B1DUW4N D3NGDUT 0M3GGG',
        link: 'https://cdn.videy.co/hbSLjyZz1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1JB3RS 1MUT B3RM4SK3R',
        link: 'https://cdn.videy.co/QaxcxkmN1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1 R3K4M D14M" D1 H0T3L S44T NGW BRG 4Y4NK',
        link: 'https://cdn.videy.co/3hRHaLdo1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌1BV K0S K0D3" NG4J4K EM.3L',
        link: 'https://cdn.videy.co/mG2WI8ps1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌TUK4NG D3M3N N4RUH K4M3R4 D1 T01L3T',
        link: 'https://cdn.videy.co/H4ygN5wW1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1 M3NT0Q1N S4MP3 S4K1T T4P1 N4G1H',
        link: 'https://cdn.videy.co/edavdhQs1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌STW M4ND1 B4W4 HP G4K S3NG4J4 K3P3NC3T L0V3',
        link: 'https://cdn.videy.co/aqGBfVas1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌L4G1 M4K4N D1 EW T3T4MGG4',
        link: 'https://cdn.videy.co/PPJhtfng1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1JB D3M3N B3D3.3SM3',
        link: 'https://cdn.videy.co/kM1aYGrx1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1 D4PUR NGW S4M4 M4J1K4N',
        link: 'https://cdn.videy.co/yk9Q5O6w1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4C3R NG4J4K P1KN1K D1 HUT4N. T4UNY4 D1 EW',
        link: 'https://cdn.videy.co/0pZXs2yZ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4H4S1SW1 0M3G P4K3 T1MUN JUMB0',
        link: 'https://cdn.videy.co/JdY0xzel1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌T4L3NT V3C3ZH 0M3G D3P3N 0RTU',
        link: 'https://cdn.videy.co/TI2Rnd6Y1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1S3RVH M4MP1R K3K0S4N AY4NG',
        link: 'https://cdn.videy.co/IwBLubdL1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌3ST3W3H L4G1 B3RS1H" D1AJ4K N93NT0Y',
        link: 'https://cdn.videy.co/Nxc40yMz1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M4LM1NG4N D1H0T3L B4R3NG P4C4R',
        link: 'https://cdn.videy.co/FBFsZsLg1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N1KM4TNYA D1S3P0N91N S4M4 BU RT',
        link: 'https://cdn.videy.co/VxzHnQx31.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N93NT0Y S4MP3 L3M3S D4N B3RK3R1NG4T',
        link: 'https://cdn.videy.co/ywOlTW1e1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌H1J4B3RS T0K3DH JVMB0 C0ML3K',
        link: 'https://cdn.videy.co/MN8Ifzoz1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌K0L3KS1 V1D3O SYVR B1D4N R1TA',
        link: 'https://cdn.videy.co/AxPueiGV1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌N93NT0Y B4R3NG H1J4B3RS T0BRVT',
        link: 'https://cdn.videy.co/HtdIBuY11.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌D1S3P0N91N S4M4 H1J4B3RS S3M0KS',
        link: 'https://cdn.videy.co/C20nY6yp1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌S1C4NT1K MVLVS M41N1N T3T3WNY4',
        link: 'https://cdn.videy.co/nxpfPCyh1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4S4NG4N M41N D1 K4M4R M4ND1',
        link: 'https://cdn.videy.co/BtypOgZr1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4G1 P4G1 UD4H B1R4H1 S4M4 AY4NG',
        link: 'https://cdn.videy.co/fYM3L3QQ1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌M41N S4M4 S1 B0S D1K4NT0R NYA',
        link: 'https://cdn.videy.co/WioYxBR51.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    {
        icon: 'bi bi-play-circle-fill',
        title: '📌P4S4NG4N P3LAJ4R B1K1N K0NT3N',
        link: 'https://cdn.videy.co/4sSONh9u1.mp4',
        desc: 'Streaming cepat & Gratis.',
    },
    // Tambahkan card baru di sini:
    // {
    //     icon: 'bi bi-star',
    //     title: 'Nama Fitur',
    //     link: 'https://alamat-fitur',
    //     desc: 'Deskripsi fitur.',
    // },
];

function renderFeatureCards() {
    const container = document.getElementById('features-container');
    if (!container) return;
    container.innerHTML = '';
    features.forEach(data => {
        container.innerHTML += `
        <div class="feature-card" tabindex="0">
            <span class="feature-icon" aria-label="${data.title}">
                <i class="${data.icon}"></i>
            </span>
            <div class="feature-title">${data.title}</div>
            <div class="feature-desc">
                <a href="${data.link}" target="_blank">${data.link}</a>
                <div style="font-size:.92em;color:#888;margin-top:3px;">${data.desc||''}</div>
            </div>
            <div class="feature-actions">
                <button onclick="previewDesc(this)">Preview</button>
            </div>
            <div class="ad-center">
                <iframe src="adslot.html" class="ad-iframe" frameborder="0" scrolling="no"></iframe>
            </div>
        </div>
        `;
    });
}
renderFeatureCards();
